services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - MODEL_DIR=/app/models
      - DATA_DIR=/app/data
    env_file:
      - .env

  web_client:
    build:
      context: ./web_client
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - backend
    volumes:
      - ./web_client/static/uploads:/app/static/uploads
